### PR TITLE
Release 3.0.4

### PR DESCRIPTION
**Pull request by sarathms**
Updated version to `3.0.4-rc.1` to test before release. We will bump it to `3.0.4` after we some internal testing and then tag it for the release build to publish.

Tracking issue: https://github.com/ooni/ooni.org/issues/600

### CODE REVIEW

**Review by bassosimone — COMMENTED** [review]
So far so good

**Comment by bassosimone** [comment]
@sarathms added better build instructions, created macOS build, created pre-release, published packages there.

**Comment by bassosimone** [comment]
Created v3.0.4-rc.1 and v3.0.4-rc.2 releases to test creating them from macOS and auto-updates from macOS.

**Comment by sarathms** [comment]
3.0.4 was released. Merging this.

**Pull request merged**
